name: Link Issues to PR Post Merge

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  link-issues:
    # Only run if PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true
    permissions:
      pull-requests: write
      contents: read
    uses: senzing-factory/build-resources/.github/workflows/link-issues-to-pull-request-post-merge.yaml@b4d8b531b66da53dcaef71a70285de492eff4c2b # v4
