name: Link Issues to PR Post Merge

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  link-issues:
    # Only run if PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true
    permissions:
      pull-requests: write
      contents: read
    uses: senzing-factory/build-resources/.github/workflows/link-issues-to-pull-request-post-merge.yaml@337e14c07a5ba1c8461d0f56c780dd5d829397f6 # v4
