name: Lint workflows

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint-workflows:
    permissions:
      contents: read
      packages: read
      pull-requests: write
      statuses: write
    uses: senzing-factory/build-resources/.github/workflows/lint-workflows.yaml@5054409094ee8f157395df086da166a898bbe1e9 # v4
