name: Lint workflows

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint-workflows:
    permissions:
      contents: read
      packages: read
      pull-requests: write
      statuses: write
    uses: senzing-factory/build-resources/.github/workflows/lint-workflows.yaml@b4d8b531b66da53dcaef71a70285de492eff4c2b # v4
