name: Move pr to done dependabot

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions: {}

jobs:
  move-pr-to-done-dependabot:
    permissions:
      repository-projects: write
    secrets:
      PROJECT_RW_TOKEN: ${{ secrets.PLACEKEY_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/move-pr-to-done-dependabot.yaml@b4d8b531b66da53dcaef71a70285de492eff4c2b # v4
    with:
      project: ${{ vars.PLACEKEY_PROJECT_PLACEKEY }}
